# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0002_auto_20180813_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='top_5',
            field=models.TextField(blank=True, verbose_name=b'Cinco art\xc3\xadculos m\xc3\xa1s destacados en temas relacionados con las Ciencias de la Sostenibilidad. De ser posible incluir ligas para acceder a las publicaciones.'),
        ),
        migrations.AddField(
            model_name='adscripcion',
            name='anno_nombramiento',
            field=models.PositiveSmallIntegerField(default=2018, verbose_name=b'a\xc3\xb1o de nombramiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adscripcion',
            name='catedra_conacyt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adscripcion',
            name='nombramiento',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_internacionales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de art\xc3\xadculos publicados en revistas internacionales'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_nacionales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de art\xc3\xadculos publicados en revistas nacionales'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='capitulos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de cap\xc3\xadtulos de libro publicados'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='libros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de libros publicados'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_doctorado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas a nivel Doctorado'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_licenciatura',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas a nivel Licenciatura'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_maestria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas a nivel Maestr\xc3\xada'),
        ),
    ]
