# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-22 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0003_auto_20180822_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradoacademico',
            name='documento',
        ),
        migrations.AddField(
            model_name='academico',
            name='ultimo_grado',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.grado_path, verbose_name=b'Copia de \xc3\xbaltimo grado acad\xc3\xa9mico'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_doctorado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas y concluidas a nivel Doctorado'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_doctorado_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad de tesis dirigidas y concluidas a nivel Doctorado en los \xc3\xbaltimos 5 a\xc3\xb1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_licenciatura',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas y concluidas a nivel Licenciatura'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_licenciatura_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad de tesis dirigidas y concluidas a nivel Licenciatura en los \xc3\xbaltimos 5 a\xc3\xb1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_maestria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de tesis dirigidas y concluidas a nivel Maestr\xc3\xada'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_maestria_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad de tesis dirigidas y concluidas a nivel Maestr\xc3\xada en los \xc3\xbaltimos 5 a\xc3\xb1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='top_5',
            field=models.TextField(blank=True, verbose_name=b'Cinco publicaciones m\xc3\xa1s destacadas en temas relacionados con las Ciencias de la Sostenibilidad. De ser posible incluir ligas para acceder a las publicaciones.'),
        ),
    ]
