# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0005_auto_20180906_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='nivel_PRIDE',
        ),
        migrations.AddField(
            model_name='academico',
            name='estimulo_UNAM',
            field=models.CharField(choices=[(b'ninguno', b'ninguno'), (b'Equivalencia', b'Equivalencia'), (b'PEPASIG', b'PEPASIG'), (b'PEI', b'PEI'), (b'PEDMETI', b'PEDMETI'), (b'PRIDE A', b'PRIDE A'), (b'PRIDE B', b'PRIDE B'), (b'PRIDE C', b'PRIDE C'), (b'PRIDE D', b'PRIDE D')], default=b'ninguno', max_length=15, verbose_name=b'Est\xc3\xadmulo UNAM'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion1',
            field=models.CharField(max_length=350, verbose_name=b'direcci\xc3\xb3n del lugar de trabajo'),
        ),
    ]
