# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0006_auto_20180906_1418'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='anexo_estimulo',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.anexo_academico_estimulo_path),
        ),
    ]
