# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0009_auto_20180912_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='doctorado_directo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='opcion_titulacion',
            field=models.BooleanField(default=False, verbose_name=b'Opci\xc3\xb3n a titulaci\xc3\xb3n'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='plan',
            field=models.CharField(choices=[('Maestr\xeda', 'Maestr\xeda'), ('Doctorado', 'Doctorado')], max_length=20),
        ),
    ]
