# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0013_auto_20180921_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='semestre_graduacion',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='semestre de graduaci\xf3n'),
        ),
    ]
