# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0014_auto_20180921_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='curp',
            field=models.CharField(max_length=100, verbose_name=b'CURP. Si usted es extranjero(a) y no cuenta con este dato, ingresar la palabra extranjero(a)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rfc',
            field=models.CharField(max_length=100, verbose_name=b'RFC. Si usted es extranjero(a) y no cuenta con este dato, ingresar la palabra extranjero(a)'),
        ),
    ]
