# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0015_auto_20181002_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles Personales'},
        ),
        migrations.AlterUniqueTogether(
            name='institucion',
            unique_together=set([('nombre', 'suborganizacion')]),
        ),
    ]
