# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0017_auto_20181018_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='top_5',
            field=models.TextField(blank=True, verbose_name=b'Cinco publicaciones m\xc3\xa1s destacadas en temas relacionados con las\n        Ciencias de la Sostenibilidad.  De ser posible incluir ligas\n        para acceder a las publicaciones.'),
        ),
    ]
