# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-10 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0018_auto_20181019_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='resumen_completo',
            field=models.BooleanField(default=False),
        ),
    ]
