# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-10 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0019_academico_resumen_completo'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='perfil_personal_completo',
            field=models.BooleanField(default=False),
        ),
    ]
