# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-10 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0020_academico_perfil_personal_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='tutor_otros_programas',
        ),
        migrations.AlterField(
            model_name='academico',
            name='comite_doctorado_otros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name=b'Cantidad total de participaciones como miembro de comit\xc3\xa9\n        tutor (no tutor principal) de estudiantes graduados de nivel\n        doctorado.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tutor_principal_otros_programas',
            field=models.TextField(blank=True, verbose_name=b'Nombres de los otros programas de posgrado en los que participa'),
        ),
    ]
