# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-25 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0022_anexoexpediente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexoexpediente',
            options={'verbose_name_plural': 'Expedientes'},
        ),
        migrations.AlterField(
            model_name='academico',
            name='resumen_completo',
            field=models.BooleanField(default=False, verbose_name=b'perfil acad\xc3\xa9mico completo'),
        ),
    ]
