# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-08 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0023_auto_20181125_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='semaforo_doctorado',
            field=models.CharField(choices=[(b'verde', b'verde'), (b'amarillo', b'amarillo'), (b'rojo', b'rojo')], default=b'rojo', max_length=10),
        ),
        migrations.AddField(
            model_name='academico',
            name='semaforo_maestria',
            field=models.CharField(choices=[(b'verde', b'verde'), (b'amarillo', b'amarillo'), (b'rojo', b'rojo')], default=b'rojo', max_length=10),
        ),
    ]
