# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-17 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0024_auto_20190108_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='CVU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N\xfamero de CVU'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='anexo_solicitud',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.anexo_academico_solicitud_path, verbose_name='Carta de solicitud de acreditaci\xf3n como tutor'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_internacionales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de art\xedculos publicados en revistas internacionales'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_internacionales_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de art\xedculos publicados en revistas internacionales durante los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_nacionales',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de art\xedculos publicados en revistas nacionales'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='articulos_nacionales_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de art\xedculos publicados en revistas nacionales durante los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='capitulos',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de cap\xedtulos de libro publicados'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='capitulos_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de cap\xedtulos de libro publicados durante los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='comite_doctorado_otros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de participaciones como miembro de comit\xe9\n        tutor (no tutor principal) de estudiantes graduados de nivel\n        doctorado.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='comite_maestria_otros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de participaciones como miembro de comit\xe9\n        tutor (no tutor principal) de estudiantes graduados de nivel\n        maestr\xeda en otros programas.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='disponible_miembro',
            field=models.BooleanField(default=False, verbose_name='Disponible como miembro de comit\xe9 tutor (asesor\xeda de alumnos)'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='disponible_tutor',
            field=models.BooleanField(default=False, verbose_name='Disponible como tutor principal (direcci\xf3n de alumnos)'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='estimulo_UNAM',
            field=models.CharField(choices=[(b'ninguno', b'ninguno'), (b'Equivalencia', b'Equivalencia'), (b'PEPASIG', b'PEPASIG'), (b'PEI', b'PEI'), (b'PEDMETI', b'PEDMETI'), (b'PRIDE A', b'PRIDE A'), (b'PRIDE B', b'PRIDE B'), (b'PRIDE C', b'PRIDE C'), (b'PRIDE D', b'PRIDE D')], default=b'ninguno', max_length=15, verbose_name='Est\xedmulo UNAM'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='libros_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de libros publicados durante los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='lineas',
            field=models.TextField(blank=True, verbose_name='Temas de inter\xe9s y/o experiencia en ciencias de la sostenibilidad, m\xe1ximo 10, uno por rengl\xf3n'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='motivacion',
            field=models.TextField(blank=True, verbose_name='Motivaci\xf3n para participar en el Programa, m\xe1ximo 200 palabras'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='nivel_SNI',
            field=models.CharField(choices=[(b'sin SNI', b'sin SNI'), (b'I', b'I'), (b'II', b'II'), (b'III', b'III'), (b'C', b'C'), (b'E', b'E')], max_length=15, verbose_name='Nivel SNI'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='numero_trabajador_unam',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='N\xfamero de trabajador (UNAM)'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='otras_actividades',
            field=models.TextField(blank=True, null=True, verbose_name='Si no cuenta con estudiantes graduados, indique si cuenta con\n        otras actividades acad\xe9micas como estancias de investigaci\xf3n,\n        seminarios de titulaci\xf3n, etc.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='otras_publicaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Si su productividad acad\xe9mica no se ve reflejada en las\n        publicaciones anteriores, indique si cuenta con otros\n        productos como por ejemplo informes t\xe9cnicos, memorias\n        t\xe9cnicas, desarrollo de proyectos hasta nivel ejecutivo,\n        planes y programas de desarrollo urbano, manuales, etc.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='palabras_clave',
            field=models.TextField(blank=True, verbose_name='Palabras clave de temas de inter\xe9s y/o experienciaen ciencias de la sostenibilidad, m\xe1ximo 10, una por rengl\xf3n'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='participacion_comite_doctorado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como miembro de comit\xe9 tutor (no tutor\n        principal) en el Posgrado en Ciencias de la Sostenibilidad a\n        nivel doctorado'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='participacion_comite_maestria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como miembro de comit\xe9 tutor (no tutor\n         principal) en el Posgrado en Ciencias de la Sostenibilidad a\n         nivel maestr\xeda'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='participacion_tutor_maestria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como tutor principal en el\n        Posgrado en Ciencias de la Sostenibilidad a nivel maestr\xeda'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='proyectos_sostenibilidad',
            field=models.TextField(blank=True, verbose_name='Principales proyectos relacionados con ciencias de la sostenibilidad durante los \xfaltimos cinco a\xf1os, especificar si se es responsable o colaborador.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='proyectos_vigentes',
            field=models.TextField(blank=True, verbose_name='Proyectos vigentes en los que pueden participar alumnos del PCS. Incluya fechas de terminaci\xf3n.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='resumen_completo',
            field=models.BooleanField(default=False, verbose_name='perfil acad\xe9mico completo'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_doctorado_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como tutor principal de\n        estudiantes graduados de nivel Doctorado en los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_licenciatura_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como tutor principal de\n        estudiantes " graduados a nivel Licenciatura en los \xfaltimos 5\n        a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_maestria',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total participaciones como tutor principal de estudiantes\n        graduados de nivel Maestr\xeda'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_maestria_5',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como tutor principal de estudiantes\n           graduados de nivel Maestr\xeda en los \xfaltimos 5 a\xf1os'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='top_5',
            field=models.TextField(blank=True, verbose_name='Cinco publicaciones m\xe1s destacadas en temas relacionados con las\n        Ciencias de la Sostenibilidad.  De ser posible incluir ligas\n        para acceder a las publicaciones.'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='ultimo_grado',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.grado_path, verbose_name='Copia de \xfaltimo grado acad\xe9mico'),
        ),
    ]
