# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-21 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0025_auto_20190117_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academico',
            old_name='fecha_acreditacion',
            new_name='ultima_acreditacion',
        ),
        migrations.AlterField(
            model_name='academico',
            name='comite_maestria_otros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de participaciones como miembro de comit\xe9\n        tutor (no tutor principal) de estudiantes graduados de nivel\n        maestr\xeda.'),
        ),
    ]
