# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0028_academico_fecha_acreditacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100)),
                ('clave', models.CharField(blank=True, max_length=20, null=True)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('creditos', models.PositiveSmallIntegerField()),
                ('tipo', models.CharField(choices=[('Obligatoria', b'Obligatoria'), ('Obligatorias de elecci\xf3n', 'Obligatorias de elecci\xf3n'), ('Optativa', 'Optativa')], max_length=40)),
                ('programa', models.FileField(upload_to=posgradmin.models.curso_path, verbose_name=b'Documento con descripci\xc3\xb3n extensa.')),
                ('campo_conocimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.CampoConocimiento')),
            ],
        ),
        migrations.RemoveField(
            model_name='catedra',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='catedra',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='catedra',
            name='solicitud',
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name_plural': 'Cursos'},
        ),
        migrations.RemoveField(
            model_name='curso',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='creditos',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='horas_semestre',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='tipo',
        ),
        migrations.AddField(
            model_name='curso',
            name='aula',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='contacto',
            field=models.TextField(blank=True, null=True, verbose_name=b'Contacto'),
        ),
        migrations.AddField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.TextField(blank=True, null=True, verbose_name=b'Profesores'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, verbose_name=b'A\xc3\xb1o'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='asignatura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Asignatura'),
        ),
        migrations.DeleteModel(
            name='Catedra',
        ),
    ]
