# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0029_auto_20190620_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.curso_path, verbose_name=b'Documento con descripci\xc3\xb3n extensa.'),
        ),
    ]
