# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0032_auto_20190620_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('Obligatoria', b'Obligatoria'), ('Obligatorias por campo', 'Obligatorias por campo'), ('Optativa', 'Optativa')], max_length=40),
        ),
    ]
