# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0033_auto_20190620_1322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='grupo',
        ),
        migrations.AddField(
            model_name='curso',
            name='grupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
