# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0034_auto_20190620_1333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='clave',
        ),
        migrations.AddField(
            model_name='curso',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='entidad',
            field=models.CharField(blank=True, choices=[(3, 3), (700, 700), (800, 800)], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, choices=[(b'CDMX', b'CDMX'), (b'Morelia', b'Morelia'), ('Le\xf3n', 'Le\xf3n')], max_length=80, null=True),
        ),
    ]
