# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0035_auto_20190620_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='campo_conocimiento',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='campos_de_conocimiento',
            field=models.ManyToManyField(blank=True, null=True, to='posgradmin.CampoConocimiento'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='entidad',
            field=models.CharField(blank=True, choices=[(b'3', b'3'), (b'600', b'600'), (b'700', b'700')], max_length=20, null=True),
        ),
    ]
