# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0036_auto_20190620_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='clave',
        ),
        migrations.AddField(
            model_name='asignatura',
            name='clave',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='campos_de_conocimiento',
            field=models.ManyToManyField(blank=True, to='posgradmin.CampoConocimiento'),
        ),
    ]
