# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-24 16:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0037_auto_20190620_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='pasaporte',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='titulo',
        ),
    ]
