# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-21 04:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posgradmin', '0038_auto_20191024_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anexo_CV', models.FileField(blank=True, null=True, upload_to=posgradmin.models.anexo_academico_CV_path, verbose_name='CV en extenso')),
                ('acreditacion', models.CharField(choices=[(b'candidato', b'candidato'), (b'no acreditado', b'no acreditado'), (b'baja', b'baja')], max_length=15)),
                ('fecha_acreditacion', models.DateField(blank=True, null=True)),
                ('ultima_reacreditacion', models.DateField(blank=True, null=True)),
                ('campos_de_conocimiento', models.ManyToManyField(blank=True, to='posgradmin.CampoConocimiento')),
                ('lineas_de_investigacion', models.ManyToManyField(blank=True, to='posgradmin.LineaInvestigacion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterModelOptions(
            name='academico',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Acad\xe9micos'},
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['asignatura', 'clave']},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['asignatura'], 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='estudiante',
            options={'ordering': ['user__first_name', 'user__last_name']},
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'ordering': ['nombre', 'suborganizacion'], 'verbose_name_plural': 'instituciones'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Perfiles Personales'},
        ),
    ]
