# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-21 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0039_auto_20191120_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name_plural': 'Profesores'},
        ),
    ]
