# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-11-23 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0041_asignatura_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesor',
            name='fecha_acreditacion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='lineas_de_investigacion',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='ultima_reacreditacion',
        ),
        migrations.AddField(
            model_name='profesor',
            name='fecha_alta',
            field=models.DateField(blank=True, null=True, verbose_name=b'fecha de alta'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('Obligatoria', b'Obligatoria'), ('Obligatorias por campo', 'Obligatorias por campo'), ('Optativa', 'Optativa'), ('Seminario de Doctorado', 'Seminario de Doctorado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='acreditacion',
            field=models.CharField(choices=[(b'candidato', b'candidato'), (b'no acreditado', b'no acreditado'), (b'baja', b'baja'), (b'profesor', b'profesor')], max_length=15),
        ),
    ]
