# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-26 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0042_auto_20191123_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='intersemestral',
            field=models.BooleanField(default=False),
        ),
    ]
