# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-11-27 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0043_asignatura_intersemestral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='acreditacion',
            field=models.CharField(choices=[(b'candidato', b'candidato'), (b'no acreditado', b'no acreditado'), (b'baja', b'baja'), ('informaci\xf3n incompleta', 'informaci\xf3n incompleta'), ('descalificado', 'descalificado'), (b'baja', b'baja'), (b'D', b'D'), (b'M', b'M'), (b'E', b'E')], max_length=25),
        ),
    ]
