# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-12-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0046_auto_20191127_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='intersemestral',
        ),
        migrations.AddField(
            model_name='curso',
            name='intersemestral',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='academico',
            name='acreditacion',
            field=models.CharField(choices=[(b'candidato', b'candidato'), (b'no acreditado', b'no acreditado'), ('informaci\xf3n incompleta', 'informaci\xf3n incompleta'), (b'por reacreditar D', b'por reacreditar D'), (b'por reacreditar M', b'por reacreditar M'), (b'por reacreditar E', b'por reacreditar E'), (b'baja', b'baja'), (b'D', b'D'), (b'M', b'M'), (b'E', b'E')], max_length=25),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='estado',
            field=models.CharField(choices=[('propuesta', 'propuesta'), ('rechazada', 'rechazada'), ('aceptada', 'aceptada')], default=b'propuesta', max_length=40),
        ),
    ]
