# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0047_auto_20191203_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='academico',
            name='maximo_grado',
            field=models.CharField(choices=[(b'licenciatura', b'licenciatura'), ('maestria', 'maestr\xeda'), ('doctorado', 'doctorado')], default=b'licenciatura', max_length=12),
        ),
    ]
