# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-01-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0048_academico_maximo_grado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='maximo_grado',
        ),
        migrations.AddField(
            model_name='academico',
            name='titulo_honorifico',
            field=models.CharField(choices=[('Lic.', 'Lic.'), ('Mtro.', 'Mtro.'), ('Mtra.', 'Mtra.'), ('Dr.', 'Dr.'), ('Dra.', 'Dra.')], default=b'Lic.', max_length=12),
        ),
    ]
