# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0050_auto_20200130_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='titulo_honorifico',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Mtro.', 'Mtro.'), ('Mtra.', 'Mtra.'), ('Dr.', 'Dr.'), ('Dra.', 'Dra.')], default=b'Lic.', max_length=12, null=True, verbose_name='T\xedtulo honor\xedfico (Dra., Mtro, Lic)'),
        ),
    ]
