# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2020-02-06 01:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0051_auto_20200205_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acreditacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('acreditacion', models.CharField(choices=[(b'candidato', b'candidato'), (b'candidato profesor', b'candidato profesor'), (b'no acreditado', b'no acreditado'), ('informaci\xf3n incompleta', 'informaci\xf3n incompleta'), (b'por reacreditar D', b'por reacreditar D'), (b'por reacreditar M', b'por reacreditar M'), (b'baja', b'baja'), (b'P', b'P'), (b'D', b'D'), (b'M', b'M'), (b'E', b'E')], default=b'candidato', max_length=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='campos_de_conocimiento',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user',
        ),
        migrations.AlterField(
            model_name='academico',
            name='acreditacion',
            field=models.CharField(choices=[(b'candidato', b'candidato'), (b'candidato profesor', b'candidato profesor'), (b'no acreditado', b'no acreditado'), ('informaci\xf3n incompleta', 'informaci\xf3n incompleta'), (b'por reacreditar D', b'por reacreditar D'), (b'por reacreditar M', b'por reacreditar M'), (b'baja', b'baja'), (b'P', b'P'), (b'D', b'D'), (b'M', b'M'), (b'E', b'E')], max_length=25),
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.AddField(
            model_name='acreditacion',
            name='academico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acreditaciones', to='posgradmin.Academico'),
        ),
    ]
