# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2020-02-06 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0052_auto_20200205_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acreditacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
