# Generated by Django 3.0.3 on 2020-02-15 23:07

import datetime
from django.db import migrations, models
import django.db.models.deletion
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0054_auto_20200205_1935'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acreditacion',
            options={'ordering': ['fecha'], 'verbose_name_plural': 'acreditaciones'},
        ),
        migrations.AlterField(
            model_name='academico',
            name='acreditacion',
            field=models.CharField(choices=[('candidato', 'candidato'), ('candidato profesor', 'candidato profesor'), ('no acreditado', 'no acreditado'), ('información incompleta', 'información incompleta'), ('por reacreditar D', 'por reacreditar D'), ('por reacreditar M', 'por reacreditar M'), ('baja', 'baja'), ('P', 'P'), ('D', 'D'), ('M', 'M'), ('E', 'E')], max_length=25),
        ),
        migrations.AlterField(
            model_name='academico',
            name='anexo_CV',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.anexo_academico_CV_path, verbose_name='CV en extenso'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='estimulo_UNAM',
            field=models.CharField(choices=[('ninguno', 'ninguno'), ('Equivalencia', 'Equivalencia'), ('PEPASIG', 'PEPASIG'), ('PEI', 'PEI'), ('PEDMETI', 'PEDMETI'), ('PRIDE A', 'PRIDE A'), ('PRIDE B', 'PRIDE B'), ('PRIDE C', 'PRIDE C'), ('PRIDE D', 'PRIDE D')], default='ninguno', max_length=15, verbose_name='Estímulo UNAM'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='libros',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de libros publicados'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='nivel_SNI',
            field=models.CharField(choices=[('sin SNI', 'sin SNI'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('C', 'C'), ('E', 'E')], max_length=15, verbose_name='Nivel SNI'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='participacion_tutor_doctorado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad de participaciones como tutor principal en el Posgrado en\n           Ciencias de la Sostenibilidad a nivel doctorado'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='semaforo_doctorado',
            field=models.CharField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], default='rojo', max_length=10),
        ),
        migrations.AlterField(
            model_name='academico',
            name='semaforo_maestria',
            field=models.CharField(choices=[('verde', 'verde'), ('amarillo', 'amarillo'), ('rojo', 'rojo')], default='rojo', max_length=10),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_doctorado',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de participaciones como tutor principal de\n        estudiantes graduados de nivel Doctorado'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tesis_licenciatura',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cantidad total de participaciones como tutor principal de\n        estudiantes graduados de nivel Licenciatura'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='titulo_honorifico',
            field=models.CharField(blank=True, choices=[('Lic.', 'Lic.'), ('Mtro.', 'Mtro.'), ('Mtra.', 'Mtra.'), ('Dr.', 'Dr.'), ('Dra.', 'Dra.')], default='Lic.', max_length=12, null=True, verbose_name='Título honorífico (Dra., Mtro, Lic)'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='tutor_principal_otros_programas',
            field=models.TextField(blank=True, verbose_name='Nombres de los otros programas de posgrado en los que participa'),
        ),
        migrations.AlterField(
            model_name='acreditacion',
            name='acreditacion',
            field=models.CharField(choices=[('candidato', 'candidato'), ('candidato profesor', 'candidato profesor'), ('no acreditado', 'no acreditado'), ('información incompleta', 'información incompleta'), ('por reacreditar D', 'por reacreditar D'), ('por reacreditar M', 'por reacreditar M'), ('baja', 'baja'), ('P', 'P'), ('D', 'D'), ('M', 'M'), ('E', 'E')], default='candidato', max_length=25),
        ),
        migrations.AlterField(
            model_name='acreditacion',
            name='fecha',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='archivo',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='adscripcion',
            name='anno_nombramiento',
            field=models.PositiveSmallIntegerField(verbose_name='año de nombramiento'),
        ),
        migrations.AlterField(
            model_name='adscripcion',
            name='asociacion_PCS',
            field=models.BooleanField(default=False, verbose_name='sólo para asociación con el PCS'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='estado',
            field=models.CharField(choices=[('propuesta', 'propuesta'), ('rechazada', 'rechazada'), ('aceptada', 'aceptada')], default='propuesta', max_length=40),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.curso_path, verbose_name='Documento con descripción extensa.'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('Obligatoria', 'Obligatoria'), ('Obligatorias por campo', 'Obligatorias por campo'), ('Optativa', 'Optativa'), ('Seminario de Doctorado', 'Seminario de Doctorado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='comite',
            name='tipo',
            field=models.CharField(choices=[('tutoral', 'tutoral'), ('candidatura', 'candidatura'), ('grado', 'grado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='curso',
            name='contacto',
            field=models.TextField(blank=True, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='entidad',
            field=models.CharField(blank=True, choices=[('3', '3'), ('600', '600'), ('700', '700')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='profesores',
            field=models.TextField(blank=True, null=True, verbose_name='Profesores'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, choices=[('CDMX', 'CDMX'), ('Morelia', 'Morelia'), ('León', 'León')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='curso',
            name='year',
            field=models.PositiveSmallIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='resolucion',
            field=models.CharField(choices=[('concedida', 'concedida'), ('denegada', 'denegada')], max_length=15),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='ingreso',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año de ingreso al posgrado'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(blank=True, help_text='Institución de Inscripción', limit_choices_to={'entidad_PCS': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Institucion'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='opcion_titulacion',
            field=models.BooleanField(default=False, verbose_name='Opción a titulación'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='semestre',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2)], null=True, verbose_name='semestre de ingreso al posgrado'),
        ),
        migrations.AlterField(
            model_name='gradoacademico',
            name='fecha_obtencion',
            field=models.DateField(verbose_name='Fecha de obtención de grado'),
        ),
        migrations.AlterField(
            model_name='gradoacademico',
            name='nivel',
            field=models.CharField(choices=[('licenciatura', 'licenciatura'), ('maestria', 'maestria'), ('doctorado', 'doctorado')], max_length=15),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='nombre',
            field=models.CharField(max_length=150, verbose_name='Institución u Organización'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='pais',
            field=models.CharField(blank=True, max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='suborganizacion',
            field=models.CharField(max_length=150, verbose_name='Dependencia, Entidad o Departamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='curp',
            field=models.CharField(max_length=100, verbose_name='CURP. Si usted es extranjero(a) y no cuenta con este dato, ingresar la palabra extranjero(a)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion1',
            field=models.CharField(max_length=350, verbose_name='dirección del lugar de trabajo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], max_length=1),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='headshot',
            field=models.ImageField(blank=True, null=True, upload_to=posgradmin.models.headshot_path, verbose_name='fotografía'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rfc',
            field=models.CharField(max_length=100, verbose_name='RFC. Si usted es extranjero(a) y no cuenta con este dato, ingresar la palabra extranjero(a)'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='descripcion',
            field=models.CharField(default='sesión ordinaria', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('nueva', 'nueva'), ('agendada', 'agendada'), ('atendida', 'atendida'), ('cancelada', 'cancelada')], default='nueva', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('registrar_catedra', 'Registrar Cátedra'), ('solicitar_apoyo_economico', 'Solicitar Apoyo Económico'), ('registrar_catedra', 'Registrar Cátedra'), ('solicitar_apoyo_economico', 'Solicitar Apoyo Económico'), ('solicitar_baja_tutor', 'Solicitar Baja de Tutoría en el Programa'), ('avisar_ausencia', 'Aviso de Ausencia por Sabático u Otra Razón'), ('otro', 'Otro')], max_length=100),
        ),
    ]
