# Generated by Django 3.0.3 on 2020-02-15 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0056_auto_20200215_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='fecha_acreditacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='academico',
            name='ultima_reacreditacion',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='acreditacion',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='dictamen',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True),
        ),
    ]
