# Generated by Django 3.0.3 on 2020-02-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0058_auto_20200225_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='tutor',
        ),
    ]
