# Generated by Django 3.0.3 on 2020-02-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0059_remove_academico_tutor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academico',
            name='ultima_reacreditacion',
        ),
    ]
