# Generated by Django 3.0.3 on 2020-02-27 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0060_remove_academico_ultima_reacreditacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='academicos',
            field=models.ManyToManyField(to='posgradmin.Academico'),
        ),
        migrations.CreateModel(
            name='ConvocatoriaCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('status', models.CharField(choices=[('abierta', 'abierta'), ('cerrada', 'cerrada')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Convocatorias para cursos',
                'ordering': ['year', 'semestre'],
                'unique_together': {('year', 'semestre')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='convocatoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.ConvocatoriaCurso'),
        ),
    ]
