# Generated by Django 3.0.3 on 2020-03-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0061_auto_20200226_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='academicos',
            field=models.ManyToManyField(help_text='profesores que impartirán el curso', to='posgradmin.Academico'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, help_text='dia(s) y horarios', max_length=300, null=True),
        ),
    ]
