# Generated by Django 3.0.3 on 2020-03-05 20:21

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0062_auto_20200305_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='creditos',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='programa',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.curso_path, verbose_name='Formato de curso nuevo completo.'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='academicos',
            field=models.ManyToManyField(help_text='Profesores que impartirán el curso.', to='posgradmin.Academico'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='horario',
            field=models.CharField(blank=True, help_text='Día(s) y horarios.', max_length=300, null=True),
        ),
    ]
