# Generated by Django 3.0.6 on 2020-07-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0063_auto_20200305_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, choices=[('virtual', 'virtual'), ('CDMX', 'CDMX'), ('Morelia', 'Morelia'), ('León', 'León')], max_length=80, null=True),
        ),
    ]
