# Generated by Django 3.0.6 on 2020-07-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0064_auto_20200727_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, choices=[('Virtual', 'Virtual'), ('CDMX', 'CDMX'), ('Morelia', 'Morelia'), ('León', 'León')], max_length=80, null=True),
        ),
    ]
