# Generated by Django 3.0.6 on 2020-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0066_auto_20200727_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='sede',
            field=models.CharField(blank=True, choices=[('en línea', 'en línea'), ('CDMX', 'CDMX'), ('Morelia', 'Morelia'), ('León', 'León')], max_length=80, null=True),
        ),
    ]
