# Generated by Django 3.0.6 on 2020-08-25 18:23

from django.db import migrations, models
    

class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0067_auto_20200728_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('solicitado', 'solicitado'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado'), ('publicado', 'publicado'), ('concluido', 'concluido')], default='solicitado', max_length=10),
        ),
    ]
