# Generated by Django 3.0.6 on 2020-08-25 19:10

from django.db import migrations




def activo2status(apps, schema_editor):
    Curso = apps.get_model('posgradmin', 'Curso')
    
    for c in Curso.objects.all():
        if c.activo:
            c.status = 'publicado'
        else:
            c.status = 'concluido'

        c.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0068_curso_status'),
    ]

    operations = [
         migrations.RunPython(activo2status),
    ]
