# Generated by Django 3.0.6 on 2020-08-25 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0069_auto_20200825_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='activo',
        ),
    ]
