# Generated by Django 3.0.6 on 2021-01-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0070_remove_curso_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('solicitado', 'solicitado'), ('aceptado', 'aceptado'), ('rechazado', 'rechazado'), ('cancelado', 'cancelado'), ('publicado', 'publicado'), ('concluido', 'concluido')], default='solicitado', max_length=10),
        ),
    ]
