# Generated by Django 3.0.6 on 2021-05-18 17:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0071_auto_20210128_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='doctorado_directo',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='folio_graduacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='ingreso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='medalla_alfonso_caso',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='mencion_honorifica',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='opcion_titulacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='semestre',
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='año de ingreso al posgrado')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)], verbose_name='semestre de ingreso al posgrado')),
                ('plan', models.CharField(choices=[('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('doctorado_directo', models.BooleanField(default=False)),
                ('opcion_titulacion', models.BooleanField(default=False, verbose_name='Opción a titulación')),
                ('folio_graduacion', models.CharField(blank=True, max_length=200, verbose_name='Folio de acta de examen de grado')),
                ('mencion_honorifica', models.BooleanField(default=False)),
                ('medalla_alfonso_caso', models.BooleanField(default=False, verbose_name='Medalla Alfonso Caso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Estudiante')),
                ('institucion', models.ForeignKey(blank=True, help_text='Institución de Inscripción', limit_choices_to={'entidad_PCS': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Institucion')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('estado', models.CharField(choices=[('inscrito', 'candidato'), ('egresado', 'candidato profesor'), ('graduado', 'no acreditado'), ('indeterminado', 'información incompleta'), ('baja', 'por reacreditar D'), ('suspension 1', 'por reacreditar M'), ('suspension 2', 'baja'), ('plazo adicional', 'P')], default='inscrito', max_length=25)),
                ('estudios', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='posgradmin.Estudios')),
            ],
            options={
                'verbose_name_plural': 'estados de estudios',
                'ordering': ['fecha'],
            },
        ),
    ]
