# Generated by Django 3.0.6 on 2021-05-18 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0072_auto_20210518_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteTutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('tipo', models.CharField(choices=[('D', 'tutor'), ('M', 'miembro de comité de doctorado'), ('T', 'tutor de doctorado'), ('A', 'tutor de maestría'), ('X', 'miembro de comité de maestría'), ('Y', 'segundo tutor de maestría'), ('Z', 'tutor principal de maestría')], default='D', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'Estudiantes y tutores',
                'ordering': ['year', 'semestre'],
            },
        ),
        migrations.RemoveField(
            model_name='comite',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='miembro1',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='miembro2',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='miembro3',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='miembro4',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='miembro5',
        ),
        migrations.RemoveField(
            model_name='comite',
            name='solicitud',
        ),
        migrations.RemoveField(
            model_name='dictamen',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='dictamen',
            name='solicitud',
        ),
        migrations.AlterModelOptions(
            name='estudios',
            options={'ordering': ['ingreso'], 'verbose_name_plural': 'estudios'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='anno_graduacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='convenio',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_graduacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='motivo_baja',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='semestre_graduacion',
        ),
        migrations.AlterField(
            model_name='estadoestudios',
            name='estado',
            field=models.CharField(choices=[('inscrito', 'inscrito'), ('egresado', 'egresado'), ('graduado', 'graduado'), ('indeterminado', 'indeterminado'), ('baja', 'baja'), ('suspensión 1', 'suspensión 1'), ('suspensión 2', 'suspensión 2'), ('plazo adicional', 'plazo adicional')], default='inscrito', max_length=25),
        ),
        migrations.DeleteModel(
            name='Asistente',
        ),
        migrations.DeleteModel(
            name='Comite',
        ),
        migrations.DeleteModel(
            name='Dictamen',
        ),
        migrations.AddField(
            model_name='estudiantetutor',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Estudiante'),
        ),
        migrations.AddField(
            model_name='estudiantetutor',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Academico'),
        ),
    ]
