# Generated by Django 3.0.6 on 2021-05-18 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0073_auto_20210518_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudios',
            name='ultimo_estado',
            field=models.CharField(default='inscrito', max_length=25),
        ),
        migrations.AlterField(
            model_name='estudiantetutor',
            name='tutor',
            field=models.ForeignKey(limit_choices_to=models.Q(('acreditacion', 'D'), ('acreditacion', 'M'), ('acreditacion', 'E'), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Academico'),
        ),
    ]
