# Generated by Django 3.0.6 on 2021-06-03 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0074_auto_20210518_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estudiantetutor',
            options={'ordering': ['year', 'semestre'], 'verbose_name_plural': 'Comités tutorales'},
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='estado',
        ),
        migrations.AlterField(
            model_name='estudios',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='posgradmin.Estudiante'),
        ),
    ]
