# Generated by Django 3.0.6 on 2021-06-03 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0075_auto_20210602_1953'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstudianteTutor',
            new_name='MembresiaComite',
        ),
    ]
