# Generated by Django 3.0.6 on 2021-06-23 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0077_auto_20210602_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiacomite',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Academico'),
        ),
    ]
