# Generated by Django 3.0.6 on 2021-09-30 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0079_auto_20210930_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='observaciones',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='permiso_trabajar',
            field=models.BooleanField(default=False, verbose_name='Permiso para trabajar'),
        ),
    ]
