# Generated by Django 3.0.6 on 2021-09-30 18:12

from django.db import migrations, models

def copy_cvu(apps, schema_editor):

    Academico = apps.get_model('posgradmin', 'Academico')
    Perfil = apps.get_model('posgradmin', 'Perfil')
    
    for aca in Academico.objects.all():
        if hasattr(aca.user, 'perfil'):
            p = aca.user.perfil
            p.CVU = aca.CVU
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0081_estudiante_promedio_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='CVU',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de CVU'),
        ),
        migrations.RunPython(copy_cvu)
    ]
