# Generated by Django 3.0.6 on 2021-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0082_perfil_cvu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='CVU',
            field=models.CharField(blank=True, help_text='movido a Perfil Personal', max_length=100, null=True, verbose_name='Número de CVU'),
        ),
    ]
