# Generated by Django 3.0.6 on 2021-09-30 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0083_auto_20210930_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='promedio_ingreso',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Promedio del último grado. Dos dígitos máximo, dos decimales.'),
        ),
    ]
