# Generated by Django 3.0.6 on 2021-10-18 21:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False 
    dependencies = [
        ('posgradmin', '0084_auto_20210930_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoHistorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('comentario', models.CharField(blank=True, max_length=400, null=True)),
                ('estado', models.CharField(choices=[('inscrito', 'inscrito'), ('egresado', 'egresado'), ('graduado', 'graduado'), ('indeterminado', 'indeterminado'), ('baja', 'baja'), ('suspensión 1', 'suspensión 1'), ('suspensión 2', 'suspensión 2'), ('plazo adicional', 'plazo adicional')], default='inscrito', max_length=25)),
            ],
            options={
                'verbose_name_plural': 'estados de estudios',
                'ordering': ['fecha'],
            },
        ),
        migrations.RenameModel(
            old_name='Estudios',
            new_name='Historial',
        ),
        migrations.DeleteModel(
            name='EstadoEstudios',
        ),
        migrations.AddField(
            model_name='estadohistorial',
            name='historial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados', to='posgradmin.Historial'),
        ),
    ]
