# Generated by Django 3.0.6 on 2021-10-19 00:51

from django.db import migrations, models

def set_horas(apps, schema_editor):

    Asignatura = apps.get_model('posgradmin', 'Asignatura')

    for a in Asignatura.objects.all():
        if a.creditos == 4:
            a.horas = 32
        elif a.creditos == 8:
            a.horas = 64
        else:
            a.horas = 0

        a.save()



class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0087_auto_20211018_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='horas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(set_horas)
    ]
