# Generated by Django 3.0.6 on 2021-10-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0088_asignatura_horas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academico',
            name='disponible_miembro',
            field=models.BooleanField(default=True, verbose_name='Disponible como miembro de comité tutor (asesoría de alumnos)'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='disponible_tutor',
            field=models.BooleanField(default=True, verbose_name='Disponible como tutor principal (dirección de alumnos)'),
        ),
    ]
