# Generated by Django 3.0.6 on 2021-10-29 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0093_auto_20211028_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('memo', 'memo'), ('atendida', 'atendida'), ('solicitud', 'solicitud')], default='memo', max_length=40),
        ),
    ]
