# Generated by Django 3.0.6 on 2021-10-29 02:56

from django.db import migrations, models
import posgradmin.models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0094_auto_20211028_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=posgradmin.models.nota_path),
        ),
    ]
