# Generated by Django 3.0.6 on 2021-12-01 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0095_auto_20211028_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='asunto',
            field=models.CharField(default='asunto', max_length=100),
            preserve_default=False,
        ),
    ]
