# Generated by Django 3.0.6 on 2022-02-04 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0096_nota_asunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='modo_graduacion',
            field=models.CharField(choices=[('-', '-'), ('tesis', 'tesis'), ('reporte técnico', 'reporte técnico'), ('artículo', 'artículo'), ('protocolo de investigación doctoral', 'protocolo de investigación doctoral')], default='-', max_length=35),
        ),
    ]
