# Generated by Django 3.0.6 on 2022-02-04 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0097_historial_modo_graduacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstanciaPAEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la actividad', max_length=200)),
                ('fecha_solicitud', models.DateField(default=datetime.date.today, verbose_name='Fecha de solicitud')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('monto_otorgado', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto otorgado en pesos mexicanos')),
                ('tipo', models.CharField(choices=[('curso', 'curso'), ('congreso', 'congreso'), ('estancia', 'estancia')], default='estancia', max_length=25)),
                ('estado', models.CharField(choices=[('solicitado', 'solicitado'), ('otorgado', 'otorgado'), ('rechazado', 'rechazado'), ('concluido', 'concluido'), ('sin producto', 'sin producto')], default='solicitado', max_length=25)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Estudiante')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.Institucion')),
            ],
        ),
    ]
