# Generated by Django 3.0.6 on 2022-02-04 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0098_estanciapaep'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estanciapaep',
            options={'verbose_name_plural': 'Estancias PAEP'},
        ),
    ]
