# Generated by Django 3.0.6 on 2022-02-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0099_auto_20220204_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estanciapaep',
            name='tipo',
            field=models.CharField(choices=[('curso', 'curso'), ('congreso', 'congreso'), ('estancia', 'estancia'), ('encuentro', 'encuentro'), ('otro', 'otro')], default='estancia', max_length=25),
        ),
    ]
