# Generated by Django 3.0.6 on 2022-02-23 18:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0101_auto_20220223_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='nombre',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='aprobado',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='campo_conocimiento',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='solicitud',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
