# Generated by Django 3.0.6 on 2022-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0102_auto_20220223_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='fecha',
            field=models.DateField(),
        ),
    ]
