# Generated by Django 3.2 on 2022-05-20 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posgradmin', '0104_auto_20220310_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='proponente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
