# Generated by Django 3.2.13 on 2022-06-16 22:17

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Estudiante = apps.get_model("posgradmin", "Estudiante")
    db_alias = schema_editor.connection.alias

    for e in Estudiante.objects.using(db_alias).all():
        if e.historial.count() > 0:
            ultimo_estado = e.historial.latest('fecha').estado
        else:
            ultimo_estado = None

        e.estado = ultimo_estado
        e.save()


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0105_asignatura_proponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='estado',
            field=models.CharField(blank=True, choices=[('inscrito', 'inscrito'), ('egresado', 'egresado'), ('graduado', 'graduado'), ('indeterminado', 'indeterminado'), ('baja', 'baja'), ('suspensión 1 sem', 'suspensión 1 sem'), ('suspensión 2 sem', 'suspensión 2 sem'), ('plazo adicional', 'plazo adicional')], max_length=25, null=True),
        ),
        migrations.RunPython(forwards_func, reverse_func)
    ]
