# Generated by Django 3.2.15 on 2022-09-22 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0108_estudiante_plan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='institucion',
            unique_together={('nombre', 'suborganizacion', 'estado', 'pais')},
        ),
    ]
