# Generated by Django 3.2.15 on 2023-02-03 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0111_auto_20221114_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='estado',
            field=models.CharField(choices=[('memo', 'memo'), ('denuncia', 'denuncia'), ('atendida', 'atendida'), ('solicitud', 'solicitud')], default='memo', max_length=40),
        ),
    ]
