# Generated by Django 3.2.15 on 2023-02-03 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0112_alter_nota_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gradoacademico',
            options={'ordering': ('-fecha_obtencion',), 'verbose_name_plural': 'Grados académicos'},
        ),
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['-fecha', '-year', '-semestre'], 'verbose_name_plural': 'Historial'},
        ),
    ]
