# Generated by Django 3.2.15 on 2023-02-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0113_auto_20230202_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='doctorado_directo',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='opcion_titulacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='doctorado_directo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='opcion_titulacion',
            field=models.BooleanField(default=False, verbose_name='Opción a titulación'),
        ),
    ]
