# Generated by Django 3.2.15 on 2023-02-10 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0114_auto_20230210_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historial',
            name='campo_conocimiento',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='lineas_investigacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='campo_conocimiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.campoconocimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lineas_investigacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.lineainvestigacion'),
        ),
    ]
