# Generated by Django 3.2.15 on 2023-03-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0116_auto_20230210_1041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstanciaPAEP',
            new_name='ApoyoMovilidad',
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ['-fecha']},
        ),
    ]
