# Generated by Django 3.2.15 on 2023-03-08 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0118_auto_20230305_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=333)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
