# Generated by Django 3.2.15 on 2023-03-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0119_invitado'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiacomite',
            name='invitado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posgradmin.invitado'),
        ),
        migrations.AlterField(
            model_name='invitado',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
