# Generated by Django 3.2.15 on 2023-03-08 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0120_auto_20230307_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membresiacomite',
            name='invitado',
        ),
        migrations.CreateModel(
            name='InvitadoMembresiaComite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2)])),
                ('tipo', models.CharField(choices=[('D', 'tutor'), ('M', 'miembro de comité de doctorado'), ('T', 'tutor de doctorado'), ('A', 'tutor de maestría'), ('X', 'miembro de comité de maestría'), ('Y', 'segundo tutor de maestría'), ('Z', 'tutor principal de maestría')], default='D', max_length=25)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.estudiante')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.invitado')),
            ],
            options={
                'verbose_name_plural': 'Invitados en Comités Tutorales',
                'ordering': ['year', 'semestre'],
            },
        ),
    ]
