# Generated by Django 3.2.15 on 2023-03-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0123_alter_acreditacion_acreditacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitadomembresiacomite',
            name='tipo',
            field=models.CharField(choices=[('E', 'asesor externo')], default='D', max_length=25),
        ),
    ]
