# Generated by Django 3.2.15 on 2023-03-17 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0125_auto_20230317_1403'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={'verbose_name_plural': 'Sedes de estudio'},
        ),
        migrations.AlterUniqueTogether(
            name='sede',
            unique_together={('estudiante', 'plan')},
        ),
    ]
