# Generated by Django 3.2.15 on 2023-03-26 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0127_auto_20230321_1925'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiembroJuradoGraduacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.academico')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.graduado')),
            ],
            options={
                'verbose_name_plural': 'Académicos en Jurados de Graduación',
            },
        ),
        migrations.CreateModel(
            name='InvitadoJuradoGraduacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.graduado')),
                ('invitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgradmin.invitado')),
            ],
            options={
                'verbose_name_plural': 'Invitados en Jurados de Graduación',
            },
        ),
    ]
