# Generated by Django 3.2.15 on 2023-04-13 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0128_invitadojuradograduacion_miembrojuradograduacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitadojuradograduacion',
            name='rol_examen',
            field=models.CharField(choices=[('presidente', 'presidente'), ('secretario', 'secretario'), ('vocal 1', 'vocal 1'), ('vocal', 'vocal'), ('ausente', 'ausente')], default='D', max_length=25),
        ),
        migrations.AddField(
            model_name='invitadojuradograduacion',
            name='rol_invitado',
            field=models.CharField(choices=[('presidente', 'presidente'), ('secretario', 'secretario'), ('vocal 1', 'vocal 1'), ('vocal', 'vocal')], default='D', max_length=25),
        ),
        migrations.AddField(
            model_name='miembrojuradograduacion',
            name='rol_examen',
            field=models.CharField(choices=[('presidente', 'presidente'), ('secretario', 'secretario'), ('vocal 1', 'vocal 1'), ('vocal', 'vocal'), ('ausente', 'ausente')], default='D', max_length=25),
        ),
        migrations.AddField(
            model_name='miembrojuradograduacion',
            name='rol_invitado',
            field=models.CharField(choices=[('presidente', 'presidente'), ('secretario', 'secretario'), ('vocal 1', 'vocal 1'), ('vocal', 'vocal')], default='D', max_length=25),
        ),
    ]
