# Generated by Django 3.2.15 on 2023-04-13 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0129_auto_20230413_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduado',
            old_name='modo_graduacion',
            new_name='modalidad_graduacion',
        ),
    ]
