# Generated by Django 3.2.15 on 2023-04-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0130_rename_modo_graduacion_graduado_modalidad_graduacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historial',
            options={'ordering': ['year', 'semestre'], 'verbose_name_plural': 'Historial'},
        ),
    ]
