# Generated by Django 3.2.15 on 2023-04-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0131_alter_historial_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresiacomite',
            name='tipo',
            field=models.CharField(choices=[('M', 'miembro de comité de doctorado'), ('T', 'tutor de doctorado'), ('A', 'tutor de maestría'), ('X', 'miembro de comité de maestría'), ('Y', 'segundo tutor de maestría'), ('Z', 'tutor principal de maestría')], default='D', max_length=25),
        ),
    ]
