# Generated by Django 3.2.15 on 2023-05-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0132_alter_membresiacomite_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatoriacurso',
            name='status',
            field=models.CharField(choices=[('abierta', 'abierta'), ('rev CA', 'revisión CA'), ('cerrada', 'cerrada')], max_length=10),
        ),
    ]
