# Generated by Django 3.2.15 on 2023-05-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0134_rename_rol_invitado_miembrojuradograduacion_rol_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitadojuradograduacion',
            old_name='rol_invitado',
            new_name='rol_asignado',
        ),
    ]
