# Generated by Django 3.2.15 on 2023-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0135_rename_rol_invitado_invitadojuradograduacion_rol_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
