# Generated by Django 3.2.15 on 2023-05-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0137_rename_observaciones_curso_observaciones_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='observaciones_profesores',
            field=models.TextField(blank=True, help_text='Observaciones de profesores'),
        ),
    ]
