# Generated by Django 3.2.15 on 2023-06-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgradmin', '0138_alter_curso_observaciones_profesores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitadomembresiacomite',
            name='tipo',
            field=models.CharField(choices=[('AEM', 'Asesor externo maestría'), ('AED', 'Asesor Externo Doctorado')], default='D', max_length=25),
        ),
        migrations.AlterField(
            model_name='membresiacomite',
            name='tipo',
            field=models.CharField(choices=[('TPD', 'Tutor(a) principal de Doctorado'), ('CD', 'Cotutor(a) de Doctorado'), ('MCD', 'Miembro de comité de Doctorado'), ('TPM', 'Tutor(a) principal de Maestría'), ('CM', 'Cotutor(a) de Maestría'), ('MCM', 'Miembro de comité de Maestría')], default='D', max_length=25),
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
    ]
